config/routes.rb
Docly3::Application.routes.draw do
  resources :pages do
    collection do
      put :update_attribute_on_the_spot_in_tree
    end
  end

  root :to => 'static#index'

    match '/password/:pagename' => 'static#password'
    match '/authenticate' => 'static#authenticate'
  
    match '/:pagename' => 'pages#show'
  
  
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_secure_password
  # validates_uniqueness_of :pagename, :on => :create
  
  before_save :nl2br
  
  private
  
  def nl2br
    # if self.pagebody
    #   self.pagebody = self.pagebody.gsub(/(\r)?\n/, "<br />")
    # end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  can_edit_on_the_spot_in_tree
  
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    if params[:pagename] or params[:pages][:pagename]
      @page = Page.find_by_pagename(params[:pagename])
    else
      @page = Page.find(params[:id])
    end
    if @page
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @page }
      end
    else
      respond_to do |format|
        format.html { redirect_to "/", :notice => 'Page was not found.'}
        format.json { render json: @page }
      end
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @pagelookup = Page.find_by_pagename(params[:page][:pagename])
    if @pagelookup
      redirect_to "/" + params[:page][:pagename]
      return
    end
    
    @page = Page.new(params[:page])
    @page.pagesecured = false

    respond_to do |format|
      if @page.save
        session[:page_id] = @page.id
        format.html { redirect_to "/" + @page.pagename, :notice => 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])
    # params[:page][:pagebody] = nl2br(params[:value])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, :notice => 'Page was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :ok }
    end
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    @page = Page.new
    @pages = Page.paginate :page => params[:page], :per_page => 10, :order => 'created_at DESC', :conditions => ['pagesecured != true']
    
  end
  
  def authenticate
    page = Page.find_by_pagename(params[:pages][:pagename])
    if page && page.authenticate(params[:pages][:password])
      session[:page_id] = page.id
      redirect_to "/" + params[:pages][:pagename], :notice => "Logged in"
    else
      redirect_to "/password/" + params[:pages][:pagename], :notice => 'Invalid password.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Docly</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%# javascript_include_tag :on_the_spot %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= link_to image_tag("docly2.png", :align => "left"), "/"%>
	<br/><br/><br/>
	
<%= yield %>

<center><p>&copy; 2011 <%= link_to "Numly, inc.", "http://numly.com" %> | <a href="/about">About Docly</a></p></center>
</body>
</html>

app/views/pages/_form.html.erb
<div id="generalform">
	
	<%= form_for(@page) do |f| %>
	  <% if @page.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

	      <ul>
	      <% @page.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="field">
	    <%= f.label "page name" %><br />
	    <%= f.text_field :pagename %>
	  </div>
	  <div class="field">
	    <%= f.label "password" %><br />
	    <%= f.password_field :password %>
	  </div>
	  <div class="actions">
	    <p><%= f.submit %></p>
	  </div>
	<% end %>
	
</div>

app/views/pages/_formold.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pagename %><br />
    <%= f.text_field :pagename %>
  </div>
  <div class="field">
    <%= f.label :pagetitle %><br />
    <%= f.text_field :pagetitle %>
  </div>

<!-- <p>Pagetitle: <%# on_the_spot_edit @page, :pagetitle %></p> -->

  <div class="field">
    <%= f.label :pagebody %><br />
    <%= f.text_area :pagebody %>
  </div>
  <div class="field">
    <%= f.label :pagesecured %><br />
    <%= f.check_box :pagesecured %>
  </div>
  <div class="actions">
    <p><%= f.submit %></p>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Pagename</th>
    <th>Pagetitle</th>
    <th>Pagebody</th>
    <th>Password digest</th>
    <th>Pagesecured</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.pagename %></td>
    <td><%= page.pagetitle %></td>
    <td><%= page.pagebody %></td>
    <td><%= page.password_digest %></td>
    <td><%= page.pagesecured %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<center>
<h1>New Page</h1>
<%= render 'form' %>

<%= link_to 'Home', root_path %>
</center>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <p>
  <b>Pagename:</b>
  <%# @page.pagename %>
</p> -->

<center>
<% if session[:page_id] == @page.id %>

	<h1>
		<div id="generalform">
		
		<% if @page.pagetitle %>
			<%= on_the_spot_in_tree_edit @page, :pagetitle, :tooltip => "Click to edit page title" %>
		<% else %>
			<%= on_the_spot_in_tree_edit @page, :pagetitle, :display_text => "Page Title", :tooltip => "Click to edit page title" %>
		<% end %>
		</div>
	</h1>

	<div id="contentwrap">

		<div id="generalform">
		<p>
			<% if @page.pagebody %>
				<%= on_the_spot_in_tree_edit @page, :pagebody, :type => :textarea, :rows => "20", :columns => "60" %>
			<% else %>
				<%= on_the_spot_in_tree_edit @page, :pagebody, :type => :textarea, :rows => "20", :columns => "60", :display_text => "Page Body" %>
			<% end %>
			<%#raw(@page.pagebody)%>
		</p>
		</div>


<!-- <p>
  <b>Pagesecured:</b>
  <%# @page.pagesecured %>
</p> -->

	</div>
	
	<div id="generalform">
	<p>
		
		<%# if @page.copyright %>
			<%# on_the_spot_in_tree_edit @page, :copyright, :type => :select, :data => [["All Rights Reserved", 'All Rights Reserved'], ["http://creativecommons.org/licenses/by/3.0/", 'Creative Commons Attribution 3.0 Unported'], ["http://creativecommons.org/licenses/by-sa/3.0/", 'Attribution-ShareAlike 3.0 Unported'], ["http://creativecommons.org/licenses/by-nc/3.0/", 'Attribution-NonCommercial 3.0 Unported'], ["http://creativecommons.org/licenses/by-nd/3.0/", 'Attribution-NoDerivs 3.0 Unported'], ["http://creativecommons.org/licenses/by-nc-nd/3.0/", 'Attribution-NonCommercial-NoDerivs 3.0 Unported'], ["http://creativecommons.org/licenses/publicdomain/", 'Public Domain'], ["http://creativecommons.org/publicdomain/zero/1.0/", 'CC0 1.0 Universal']] %>
		<%# else %>
			<%# on_the_spot_in_tree_edit @page, :copyright, :type => :select, :display_text => "All Rights Reserved",:data => [["All Rights Reserved", 'All Rights Reserved'], ["http://creativecommons.org/licenses/by/3.0/", 'Creative Commons Attribution 3.0 Unported'], ["http://creativecommons.org/licenses/by-sa/3.0/", 'Attribution-ShareAlike 3.0 Unported'], ["http://creativecommons.org/licenses/by-nc/3.0/", 'Attribution-NonCommercial 3.0 Unported'], ["http://creativecommons.org/licenses/by-nd/3.0/", 'Attribution-NoDerivs 3.0 Unported'], ["http://creativecommons.org/licenses/by-nc-nd/3.0/", 'Attribution-NonCommercial-NoDerivs 3.0 Unported'], ["http://creativecommons.org/licenses/publicdomain/", 'Public Domain'], ["http://creativecommons.org/publicdomain/zero/1.0/", 'CC0 1.0 Universal']] %>
			<%# on_the_spot_in_tree_edit @page, :copyright, :type => :select, :display_text => "All Rights Reserved",:data => [[1, 'All Rights Reserved'], [2, 'Creative Commons Attribution 3.0 Unported'], [3, 'Attribution-ShareAlike 3.0 Unported'], [4, 'Attribution-NonCommercial 3.0 Unported'], [5, 'Attribution-NoDerivs 3.0 Unported'], [6, 'Attribution-NonCommercial-NoDerivs 3.0 Unported'], [7, 'Public Domain'], [8, 'CC0 1.0 Universal']] %>
		<%# end %>
	</p>
	</div>

<% else %>

<h1>
<%=@page.pagetitle rescue ""%>
</h1>

<div id="contentwrap">
	<%=raw(@page.pagebody.gsub(/(\r)?\n/, "<br />"))  rescue ""%>
</div>	
<%= link_to 'Edit page', "/password/" + @page.pagename   rescue ""%> |

<% end %>

	
	<%= link_to 'Create new page', new_page_path %>

</center>